---
title: "Boxhead Analysis"
author: "Ling L.D."
date: "November 13, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
```

Helper functions:
```{r}
isEven <- function(num){
  return (num %% 2 == 0)
}
```

Getting data files:
```{r}
filenames = list.files(path = ".", pattern = ".csv")
```


```{r}
responses <- read.csv("responses.csv", as.is = TRUE)
pids <- as.data.frame(matrix(nrow = nrow(responses), ncol = 22 + 6))
colnames(pids) <- c("exp", "PID", "age", "male", "Social.Jibo", "PA.easy", "PA.hard", "PA.etime", "PA.htime", "WA.easy", "WA.hard", "WA.htime", "WA.etime", "RC.easy", "RC.hard", "RC.etime", "RC.htime", "cs1", "cs2", "cs3", "cs4", "rExposure", "empathy", "self.efficacy", "BFI.extraversion", "BFI.neuroticism", "jpn", "invalid")
for (i in 1:nrow(responses)){
  pids[i, 1] <- isEven(responses[i, 2])
  pids[i, 2:3] <- responses[i, 2:3]
  pids[i, 4] <- responses[i, 4] == "Male"
  pids[i, 5] <- responses[i, 9]
  pids[i, "jpn"] <- responses[i, 2] %in% c(546, 57, 910, 696, 214)
  pids[i, "invalid"] <- responses[i, 2] %in% c(778, 957, 440, 963, 63, 
                                             804, 381, 764, 97, 21, 228)
}
```

Questionnaire score calculation:
```{r}
csrScore <- function(i){
  cs.resp <- responses[i, 5]
  r.resp <- responses[i, 6]
  cs1 <- "never programmed before"
  cs2 <- "consider myself a novice"
  cs3 <- "intermediate programmer"
  cs4 <- "major component"
  r1 <- "movies"
  r2 <- "home or workplace"
  r3 <- "study"
  r4 <- "social interaction"
  r5 <- "programmed"
  return (c(length(grep(cs1, cs.resp)), length(grep(cs2, cs.resp)),
  length(grep(cs3, cs.resp)), length(grep(cs4, cs.resp)),
  length(c(grep(r1, r.resp), grep(r2, r.resp), grep(r3, r.resp),
  grep(r4, r.resp), grep(r5, r.resp)))))
}

getMeanScore <- function(i, inds, rev, maxsc){
  rscp <- responses
  for (r in rev){
    rscp[i, r] <- maxsc - responses[i, r] + 1
  }
  df <- rscp[i, inds]
  sum <- 0
  for (c in inds){
    sum = sum + rscp[i, c]
  }
  return (sum/length(inds))
}

for (i in 1:nrow(responses)){
  pids[i, 18:21] <- csrScore(i)[1:4]
  pids[i, "rExposure"] <- csrScore(i)[5]
  inds <- 21:34
  rev <- c(22, 25, 29, 32, 33) # Reverse scored!
  pids[i, "empathy"] <- getMeanScore(i, inds, rev, 7)
  inds <- 35:47
  rev <- c(37, 38, 39, 40, 43, 44, 46) # Reverse scored!
  pids[i, "self.efficacy"] <- getMeanScore(i, inds, rev, 7)
  inds <- c(48, 53, 58, 68, 73, 78, 83)
  rev <- c(53, 68, 78)
  pids[i, "BFI.extraversion"] <- getMeanScore(i, inds, rev, 7)
  inds <- c(51, 56, 61, 66, 71, 76, 81, 86)
  rev <- c(56, 71, 81)
  pids[i, "BFI.neuroticism"] <- getMeanScore(i, inds, rev, 7)
}

t.test(pids$cs1[pids$exp == 1], pids$cs1[pids$exp == 0])
t.test(pids$cs2[pids$exp == 1], pids$cs2[pids$exp == 0])
t.test(pids$cs3[pids$exp == 1], pids$cs3[pids$exp == 0])
t.test(pids$cs4[pids$exp == 1], pids$cs4[pids$exp == 0])

t.test(pids$rExposure[pids$exp == 1], pids$rExposure[pids$exp == 0])
t.test(pids$empathy[pids$exp == 1], pids$empathy[pids$exp == 0])
t.test(pids$self.efficacy[pids$exp == 1], pids$self.efficacy[pids$exp == 0])#**
t.test(pids$BFI.extraversion[pids$exp == 1], pids$BFI.extraversion[pids$exp == 0])
t.test(pids$BFI.neuroticism[pids$exp == 1], pids$BFI.neuroticism[pids$exp == 0])

t.test(pids$male[pids$exp == 1], pids$male[pids$exp == 0])
t.test(pids$age[pids$exp == 1], pids$age[pids$exp == 0])
```


Manipulation check:
```{r}
# Mean social scores for Jibo: exp vs. control
t.test(pids$Social.Jibo[pids$exp == 1], pids$Social.Jibo[pids$exp == 0])
socialsc <- aov(Social.Jibo ~ exp, data = pids)
summary(socialsc)
# p = .19, t = 1.34, means = 5.88, 4.7
getMeanSD <- function(var){
  print(paste("Mean, SD E:", mean(var[pids$exp == 1]), sd(var[pids$exp == 1])))
  print(paste("Mean, SD C:", mean(var[pids$exp == 0]), sd(var[pids$exp == 0])))
}

getMeanSD(pids$Social.Jibo)

summary(aov(Social.Jibo ~ exp + BFI.extraversion + BFI.neuroticism + empathy + age + male + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))
# Do social scores correlate with performance?
```

PA analysis:
```{r}
for (i in 1:nrow(pids)){
  pid <- pids$PID[i]
  pafile <- filenames[grep(paste0("^", pid, "_pa"), filenames)]
  pafile <- read.csv(pafile, as.is = TRUE)
  pafile$correctness <- as.logical(pafile$correctness)
  # for time, excuse cue 0 since some skipped instructions and took extra time
  pids$PA.hard[i] <- mean(pafile$correctness[1:24])
  pids$PA.htime[i] <- mean(pafile$time[1:24][(pafile$cue != 0)[1:24]])
  pids$PA.easy[i] <- mean(pafile$correctness[25:48])
  pids$PA.etime[i] <- mean(pafile$time[25:48][(pafile$cue != 0)[25:48]])
}

t.test(pids$PA.hard, pids$PA.easy, paired = TRUE) # .75 vs .80 p = .19

mean(pids$PA.hard)
sd(pids$PA.hard)
mean(pids$PA.easy)
sd(pids$PA.easy)


plotCor <- function(mod, x, y, xlab, ylab){
  coefs <- summary(mod)$coefficients
  # y = a + bx
  b = round(coefs[2, 1], 3)
  a = round(coefs[1, 1], 3)
  eq = paste0("y = ", a, " + ", b, "x, p = ", round(coefs[2, 4], 4))
  plot(x, y, main = paste(ylab, "by", xlab), xlab = xlab, ylab = ylab, col = pids$invalid + 1, sub = eq)
  abline(a = a, b = b, col = "red")
}

cor.test(pids$Social.Jibo, pids$PA.hard) # r = 0.29, B = 0.02, p = 0.10
mod = lm(formula = PA.hard ~ Social.Jibo, data = pids)
summary(mod)
plotCor(mod, pids$Social.Jibo, pids$PA.hard, "Jibo Social Scores", "Avg. Hard PA Scores")
cor.test(pids$Social.Jibo, pids$PA.easy)

mod = lm(formula = PA.easy ~ Social.Jibo, data = pids)
summary(mod)
# r = 0.39, B = 0.02, p = 0.03 SIGNIFICANT!
plotCor(mod, pids$Social.Jibo, pids$PA.easy, "Jibo Social Scores", "Avg. Easy PA Scores")

mod = lm(formula = I((pids$PA.easy + pids$PA.hard)/2) ~ Social.Jibo, data = pids)
summary(mod)
plotCor(mod, pids$Social.Jibo, I((pids$PA.easy + pids$PA.hard)/2), "Jibo Social Scores", "Avg. PA Scores")
cor.test((pids$PA.easy + pids$PA.hard)/2, pids$Social.Jibo)

# time: nothing significant
t.test(pids$PA.htime[pids$exp == 1], pids$PA.htime[pids$exp == 0])
t.test(pids$PA.etime[pids$exp == 1], pids$PA.etime[pids$exp == 0])
t.test((pids$PA.etime[pids$exp == 1] + pids$PA.htime[pids$exp == 1])/2, 
       (pids$PA.etime[pids$exp == 0] + pids$PA.htime[pids$exp == 0])/2)

summary(lm(formula = PA.easy ~ Social.Jibo + jpn, data = pids))
summary(lm(formula = I((pids$PA.easy + pids$PA.hard)/2) ~ Social.Jibo + jpn, data = pids))

plotvar <- pids$Social.Jibo
scoredf <- as.data.frame(matrix(nrow = 2, ncol = 2))
colnames(scoredf) <- c("mean", "sd")
scoredf[1, ] <- c(mean(plotvar[pids$exp == 1]), sd(plotvar[pids$exp == 1]))
scoredf[2, ] <- c(mean(plotvar[pids$exp == 0]), sd(plotvar[pids$exp == 0]))
bp <- barplot(scoredf$mean, main = "Ratings of Jibo Sociality by Condition", 
        names.arg = c("Experimental", "Control"), col = 4:2, ylim = c(0, 7), sub = "(+-1 SD shown)")
arrows(x0 = bp , y0 = min(scoredf$mean + scoredf$sd, 7.0), y1 = scoredf$mean - scoredf$sd, 
       angle = 90, code = 3)

plotmean95 <- function(plotvar, vartitle){
  scoredf <- as.data.frame(matrix(nrow = 2, ncol = 2))
  colnames(scoredf) <- c("mean", "sd")
  scoredf[1, ] <- c(mean(plotvar[pids$exp == 1]), sd(plotvar[pids$exp == 1]))
  scoredf[2, ] <- c(mean(plotvar[pids$exp == 0]), sd(plotvar[pids$exp == 0]))
  bp <- barplot(scoredf$mean, main = paste(vartitle, "by Condition"), 
          names.arg = c("Experimental", "Control"), col = 4:2, ylim = c(0, 1), sub = "(+-1 SD shown)")
  arrows(x0 = bp , y0 = scoredf$mean - scoredf$sd, y1 = min(scoredf$mean + scoredf$sd, 1.0), 
         angle = 90, code = 3)
}

avgex = (pids$PA.hard[pids$exp == 1] + pids$PA.easy[pids$exp == 1])/2
avgctrl = (pids$PA.hard[pids$exp == 0] + pids$PA.easy[pids$exp == 0])/2
t.test(avgex, avgctrl)
scoredf <- as.data.frame(matrix(nrow = 2, ncol = 2))
colnames(scoredf) <- c("mean", "sd")
scoredf[1, ] <- c(mean(avgex), sd(avgex))
scoredf[2, ] <- c(mean(avgctrl), sd(avgctrl))
bp <- barplot(scoredf$mean, main = "Average PA Score by Condition", 
        names.arg = c("Experimental", "Control"), col = 4:2, ylim = c(0, 1))
arrows(x0 = bp , y0 = scoredf$mean + scoredf$sd, y1 = max(scoredf$mean - scoredf$sd, 1.0), 
       angle = 90, code = 3)


t.test(pids$PA.hard[pids$exp == 1], pids$PA.hard[pids$exp == 0])
plotmean95(pids$PA.hard, "Avg. Hard PA Score")

t.test(pids$PA.easy[pids$exp == 1], pids$PA.easy[pids$exp == 0])
plotmean95(pids$PA.easy, "Avg. Easy PA Score")


# hard pa tasks: exp vs. control
t.test(pids$PA.hard[pids$exp == 1], pids$PA.hard[pids$exp == 0])
summary(aov(PA.hard ~ exp, data = pids))
summary(aov(PA.hard ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure + jpn, data = pids))
# easy pa tasks: exp vs. control
t.test(pids$PA.easy[pids$exp == 1], pids$PA.easy[pids$exp == 0])
summary(aov(PA.easy ~ exp, data = pids))
summary(aov(PA.easy ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure + jpn, data = pids))

summary(aov(I((PA.easy + PA.hard)/2) ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure + jpn, data = pids))

getMeanSD(pids$PA.etime)
summary(aov(PA.etime ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure + jpn, data = pids))
getMeanSD(pids$PA.htime)
summary(aov(PA.htime ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure + jpn, data = pids))
```

WA analysis:
```{r}
wordse <- rep(0, 6)
wordsc <- rep(0, 6)
for (i in 1:nrow(pids)){
  pid <- pids$PID[i]
  wafile <- filenames[grep(paste0("^", pid, "_wa"), filenames)]
  wafile <- read.csv(wafile, as.is = TRUE)
  wafile <- wafile[wafile$valid == 1, ] # only take valid words
  pids$WA.hard[i] <- sum(wafile$stimulus %in% c("kite", "scissors", "projector"))
  pids$WA.easy[i] <- sum(wafile$stimulus %in% c("rope", "ball", "wheel"))
  pids$WA.htime[i] <- mean(wafile$time[wafile$stimulus %in% 
                               c("kite", "scissors", "projector")])
  pids$WA.etime[i] <- mean(wafile$time[wafile$stimulus %in% 
                               c("rope", "ball", "wheel")])
  if (isEven(pid))
    wordse <- wordse + c(sum(wafile$stimulus == "kite"), sum(wafile$stimulus == "scissors"), sum(wafile$stimulus == "projector"), 
                      sum(wafile$stimulus == "rope"), sum(wafile$stimulus == "ball"), sum(wafile$stimulus == "wheel"))
  else
    wordsc <- wordsc + c(sum(wafile$stimulus == "kite"), sum(wafile$stimulus == "scissors"), sum(wafile$stimulus == "projector"), 
                     sum(wafile$stimulus == "rope"), sum(wafile$stimulus == "ball"), sum(wafile$stimulus == "wheel"))
}

mean(pids$WA.easy)
sd(pids$WA.easy)
mean(pids$WA.hard)
sd(pids$WA.hard)
t.test(pids$WA.easy, pids$WA.hard, paired = TRUE) 
t.test(pids$WA.etime, pids$WA.htime, paired = TRUE) 

cor.test(pids$Social.Jibo, pids$WA.hard)
mod <- lm(formula = WA.hard ~ Social.Jibo, data = pids)
summary(mod)
plotCor(mod, pids$Social.Jibo, pids$WA.hard, "Jibo Social Scores", "Hard WA Scores")
mod <- lm(formula = WA.easy ~ Social.Jibo, data = pids)
summary(mod)
plotCor(mod, pids$Social.Jibo, pids$WA.easy, "Jibo Social Scores", "Easy WA Scores")

mod <- lm(formula = WA.etime ~ Social.Jibo, data = pids)
summary(mod)
plotCor(mod, pids$Social.Jibo, pids$WA.etime, "Jibo Social Scores", "Avg. Easy WA Times")
mod <- lm(formula = WA.htime ~ Social.Jibo, data = pids)
summary(mod)
plotCor(mod, pids$Social.Jibo, pids$WA.htime, "Jibo Social Scores", "Avg. Hard WA Times")

summary(lm(formula = WA.htime + WA.etime ~ Social.Jibo, data = pids))
plot(pids$Social.Jibo, pids$WA.htime + pids$WA.etime, main = "total WA time by Jibo Social rating", xlab = "Jibo Social rating", ylab = "total WA time", col = pids$invalid + 1, sub = "p = .08")
abline(a = 5.979, b = 0.175, col = "red")
text("y =  5.979 + 0.175x", x = 7, y = 8, col = "red")

# time
t.test(pids$WA.htime[pids$exp == 1], pids$WA.htime[pids$exp == 0])# 3.57, 3.66
summary(aov(WA.htime ~  exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))
t.test(pids$WA.etime[pids$exp == 1], pids$WA.etime[pids$exp == 0]) # 3.36, 3.23
summary(aov(WA.etime ~  exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))

# hard wa tasks: exp vs. control
t.test(pids$WA.hard[pids$exp == 1], pids$WA.hard[pids$exp == 0])
summary(aov(WA.hard ~ exp, data = pids)) #means = 23.00, 22.13
getMeanSD(pids$WA.hard)
summary(aov(WA.hard ~  exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))

plotvar = pids$WA.hard
scoredf <- as.data.frame(matrix(nrow = 2, ncol = 2))
colnames(scoredf) <- c("mean", "sd")
scoredf[1, ] <- c(mean(plotvar[pids$exp == 1]), sd(plotvar[pids$exp == 1]))
scoredf[2, ] <- c(mean(plotvar[pids$exp == 0]), sd(plotvar[pids$exp == 0]))
bp <- barplot(scoredf$mean, main = paste("Hard WA Scores", "by Condition"), 
        names.arg = c("Experimental", "Control"), col = 4:2, ylim = c(0, 30), sub = "(+-1 SD shown)")
arrows(x0 = bp , y0 = scoredf$mean + scoredf$sd, y1 = scoredf$mean - scoredf$sd, 
         angle = 90, code = 3)
  
# easy wa tasks: exp vs. control
t.test(pids$WA.easy[pids$exp == 1], pids$WA.easy[pids$exp == 0])
summary(aov(WA.easy ~ exp, data = pids)) #means = 23.88, 25.06
getMeanSD(pids$WA.easy)
summary(aov(WA.easy ~  exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))
plotvar = pids$WA.easy
scoredf <- as.data.frame(matrix(nrow = 2, ncol = 2))
colnames(scoredf) <- c("mean", "sd")
scoredf[1, ] <- c(mean(plotvar[pids$exp == 1]), sd(plotvar[pids$exp == 1]))
scoredf[2, ] <- c(mean(plotvar[pids$exp == 0]), sd(plotvar[pids$exp == 0]))
bp <- barplot(scoredf$mean, main = paste("Easy WA Scores", "by Condition"), 
        names.arg = c("Experimental", "Control"), col = 4:2, ylim = c(0, 35), sub = "(+-1 SD shown)")
arrows(x0 = bp , y0 = scoredf$mean + scoredf$sd, y1 = scoredf$mean - scoredf$sd, 
         angle = 90, code = 3)

summary(aov(WA.easy + WA.hard ~  exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))
```

RC analysis: 
```{r}
questions = rep(0, 8)
pids$RC.hread = rep(NA, nrow(pids))
pids$RC.eread = rep(NA, nrow(pids))
pids$RC.hard2 = rep(NA, nrow(pids))
pids$RC.easy2 = rep(NA, nrow(pids))
for (i in 1:nrow(pids)){
  pid <- pids$PID[i]
  rcfile <- filenames[grep(paste0("^", pid, "_rc2"), filenames)]
  rcfile <- read.csv(rcfile)
  readfile <- filenames[grep(paste0("^", pid, "_rc1"), filenames)]
  readfile <- read.csv(readfile)
  colnames(rcfile) <- c("correct", "time")
  rcfile$correct <- as.logical(rcfile$correct)
  pids$RC.hard[i] <- mean(rcfile$correct[1:4])
  pids$RC.htime[i] <- sum(rcfile$time[1:4])
  pids$RC.easy[i] <- mean(rcfile$correct[5:8])
  pids$RC.etime[i] <- sum(rcfile$time[5:8])
  pids$RC.easy2[i] <- mean(rcfile$correct[c(5, 7)])
  pids$RC.hard2[i] <- mean(rcfile$correct[2:4])
  questions = questions + rcfile$correct[1:8]
  pids$RC.hread[i] <- sum(readfile[readfile$article == "hard",]$time)
  pids$RC.eread[i] <- sum(readfile[readfile$article == "easy",]$time)
}

questions # for 2 of the easy questions, almost nobody got it wrong

cor.test(pids$Social.Jibo, pids$RC.hard)
mod <- lm(formula = RC.hard ~ Social.Jibo, data = pids)
summary(mod)
plotCor(mod, pids$Social.Jibo, pids$RC.hard, "Jibo Social Scores", "Hard RC Scores")
cor.test(pids$Social.Jibo, pids$RC.easy)
mod <- lm(formula = RC.easy ~ Social.Jibo, data = pids)
summary(mod)
plotCor(mod, pids$Social.Jibo, pids$RC.easy, "Jibo Social Scores", "Easy RC Scores")

cor.test(pids$Social.Jibo, pids$RC.hard2)
mod <- lm(formula = RC.hard2 ~ Social.Jibo, data = pids)
summary(mod)
cor.test(pids$Social.Jibo, pids$RC.easy2)
mod <- lm(formula = RC.easy2 ~ Social.Jibo, data = pids)
summary(mod)

cor.test(pids$Social.Jibo, pids$RC.easy + pids$RC.hard)
mod <- lm(formula = RC.easy + RC.hard ~ Social.Jibo, data = pids)
summary(mod)

summary(lm(formula = RC.easy + RC.hard ~ Social.Jibo, data = pids))
plot(pids$Social.Jibo, pids$RC.easy + pids$RC.hard, main = "total RC score by Jibo Social rating", xlab = "Jibo Social rating", ylab = "total RC score", sub = "p = .05", col = pids$invalid + 1)
abline(a = 0.771, b = 0.046, col = "red")
text("y = 0.771 + 0.046x", x = 7, y = 0.7, col = "red")

cor.test(pids$Social.Jibo, pids$RC.hread)
summary(lm(formula = RC.hread ~ Social.Jibo, data = pids))
cor.test(pids$Social.Jibo, pids$RC.eread)
summary(lm(formula = RC.eread ~ Social.Jibo, data = pids))
cor.test(pids$Social.Jibo, pids$RC.htime)
summary(lm(formula = RC.htime ~ Social.Jibo, data = pids))
cor.test(pids$Social.Jibo, pids$RC.etime)
summary(lm(formula = RC.etime ~ Social.Jibo, data = pids))

t.test(pids$RC.hard, pids$RC.easy, paired = TRUE)
mean(pids$RC.hard)
sd(pids$RC.hard)
mean(pids$RC.easy)
sd(pids$RC.easy)

t.test(pids$RC.hread, pids$RC.eread, paired = TRUE)
mean(pids$RC.hread)
sd(pids$RC.hread)
mean(pids$RC.eread)
sd(pids$RC.eread)

# hard rc tasks: exp vs. control
t.test(pids$RC.hard[pids$exp == 1], pids$RC.hard[pids$exp == 0])
summary(aov(RC.hard ~ exp, data = pids))
summary(aov(RC.hard ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))
getMeanSD(pids$RC.hard)
plotmean95(pids$RC.hard, "Avg. Hard RC Score")
# easy rc tasks: exp vs. control
t.test(pids$RC.easy[pids$exp == 1], pids$RC.easy[pids$exp == 0])
summary(aov(RC.easy ~ exp, data = pids))
summary(aov(RC.easy ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))
getMeanSD(pids$RC.easy)
plotmean95(pids$RC.easy, "Avg. Easy RC Score")

# time spent:
# hard pa tasks: exp vs. control
t.test(pids$RC.htime[pids$exp == 1], pids$RC.htime[pids$exp == 0])
summary(aov(RC.htime ~ exp, data = pids))
summary(aov(RC.htime ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))

# easy pa tasks: exp vs. control
t.test(pids$RC.etime[pids$exp == 1], pids$RC.etime[pids$exp == 0])
summary(aov(RC.etime ~ exp, data = pids))
summary(aov(RC.etime ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))

# reading time
t.test(pids$RC.eread[pids$exp == 1], pids$RC.eread[pids$exp == 0])
summary(aov(RC.eread ~ exp, data = pids))
summary(aov(RC.eread ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))
getMeanSD(pids$RC.eread)
plotvar = pids$RC.eread
scoredf <- as.data.frame(matrix(nrow = 2, ncol = 2))
colnames(scoredf) <- c("mean", "sd")
scoredf[1, ] <- c(mean(plotvar[pids$exp == 1]), sd(plotvar[pids$exp == 1]))
scoredf[2, ] <- c(mean(plotvar[pids$exp == 0]), sd(plotvar[pids$exp == 0]))
bp <- barplot(scoredf$mean, main = paste("Time Reading Easy Article", "by Condition"), 
        names.arg = c("Experimental", "Control"), col = 4:2, ylim = c(0, 155), sub = "(+-1 SD shown)")
arrows(x0 = bp , y0 = scoredf$mean + scoredf$sd, y1 = scoredf$mean - scoredf$sd, 
         angle = 90, code = 3)

t.test(pids$RC.hread[pids$exp == 1], pids$RC.hread[pids$exp == 0])
summary(aov(RC.hread ~ exp, data = pids))
summary(aov(RC.hread ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = pids))
getMeanSD(pids$RC.hread)
plotvar = pids$RC.hread
scoredf <- as.data.frame(matrix(nrow = 2, ncol = 2))
colnames(scoredf) <- c("mean", "sd")
scoredf[1, ] <- c(mean(plotvar[pids$exp == 1]), sd(plotvar[pids$exp == 1]))
scoredf[2, ] <- c(mean(plotvar[pids$exp == 0]), sd(plotvar[pids$exp == 0]))
bp <- barplot(scoredf$mean, main = paste("Time Reading Hard Article", "by Condition"), 
        names.arg = c("Experimental", "Control"), col = 4:2, ylim = c(0, 220), sub = "(+-1 SD shown)")
arrows(x0 = bp , y0 = scoredf$mean + scoredf$sd, y1 = scoredf$mean - scoredf$sd, 
         angle = 90, code = 3)
```

Redoing all of the tests with "valid" (Jibo didn't turn off) PIDS
```{r}
invalidpids = c(778, 957, 440, 963, 804, 381, 764, 97, 21, 228)

remPIDS = function(remlist){
  return(pids[!(pids$PID %in% remlist), ])
}

validpids = remPIDS(invalidpids)
summary(lm(formula = PA.easy ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure + jpn, data = validpids))
summary(lm(formula = PA.hard ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure + jpn, data = validpids))
summary(lm(formula = WA.easy ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))
summary(lm(formula = WA.hard ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))
summary(lm(formula = WA.etime ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))
summary(lm(formula = WA.htime ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))
summary(lm(formula = RC.easy ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))
summary(lm(formula = RC.hard ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))
summary(lm(formula = RC.etime ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))
summary(lm(formula = RC.htime ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))
summary(lm(formula = RC.eread ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))
summary(lm(formula = RC.hread ~ exp + age + male + BFI.extraversion + self.efficacy + empathy + cs1 + cs2 + cs3 + cs4 + rExposure, data = validpids))

```

